### ISSUE TITLE
"Solid Chart.js" repo is no longer available

### ISSUE THREAD

**Issue by MikaelPorttila** [one-aalam/awesome-solid-js#16]
Hi,
I noticed that the "Solid Chart.js" repo and page is no longer available.

**Comment by one-aalam** [comment]
Hey @MikaelPorttila Thank you for sharing and apologies for the late response. 

Do you mean to say that the library is no more available or useful? I strangely find the repo: https://github.com/MrFoxPro/solid-chart.js and the link: https://www.npmjs.com/package/solid-chart.js to be still up.
