### ISSUE TITLE
Include libraries from SolidHack

### ISSUE THREAD

**Issue by KaiHuebner** [one-aalam/awesome-solid-js#17]
The recent [SolidHack competition](https://github.com/solidjs/solidhack-submissions) has a list of great new apps and libraries.

**Comment by one-aalam** [comment]
Sure @KaiHuebner will consider adding the good, and practically useful libraries from there. Thank you for the recommendation.

**Comment by one-aalam** [comment]
Hey @KaiHuebner I've included some of the noteworthy apps/libraries from the SolidHack submissions. 

Please LMK if you see any other Interesting library/app I'm missing here, or better open a PR :-)
