### ISSUE TITLE
Add Astro, vite-plugin-ssr and Mitosis

### ISSUE THREAD

**Issue by orenelbaum** [one-aalam/awesome-solid-js#3]
They are part of the ecosystem, Astro has built in integration, vite-plugin-ssr doesn't have built in integration with anything but they have a working example with Solid, and Mitosis can actually compile into Solid.

**Comment by one-aalam** [comment]
Hey @orenelbaum I'll add them. Thanks!

On a side note, I actually maintain this https://github.com/one-aalam/awesome-astro so I know :-), and I've came across mitosis too. It's just didn't cross my mind, but compile-to-solid, and solid-to-string/ssr both qualify for inclusion. 

Thanks again!

**Comment by orenelbaum** [comment]
You are welcome! Keep maintaining those awesome awesome lists!
I'll keep opening issues if I find relevant projects that are not on the list already.
There are also a some libraries under the Solid Github org that are not included in here, I think that the relevant ones are:
https://github.com/solidjs/solid-jest
https://github.com/solidjs/solid-testing-library
 https://github.com/solidjs/solid-meta
https://github.com/solidjs/solid-app-router
https://github.com/solidjs/templates
https://github.com/solidjs/solid-refresh
https://github.com/solidjs/solid-transition-group

**Comment by orenelbaum** [comment]
Also, tsparticles/solid appears twice

**Comment by one-aalam** [comment]
Hey @orenelbaum It's done now. Thanks!

Please LMK, or share a PR if you discover more stuff that's missing here.
